name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Deploy
      run: |
        cd ${{ secrets.APP_DIR }}
        bash deploy.sh