name: 🌍 Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - ".github/**"
      - "!.github/workflows/deploy.yaml"
      - ".gitignore"
      - ".gitattributes"
      - "docs/**"

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Deploy
      run: |
        cd ${{ secrets.APP_DIR }}
        bash deploy.sh